### ISSUE TITLE
Are there any future plans for adding figwheel to the template ?

### ISSUE THREAD

**Issue by suvash** [magomimmo/cljs-start#15]
Just a curiosity here if it has been considered. It seems to be quite useful to have in the template.
push-reloading would really change the game !
https://github.com/bhauman/lein-figwheel

relevant issue in figwheel project here : https://github.com/bhauman/lein-figwheel/issues/34

**Comment by magomimmo** [comment]
I'll be back from vacation next week. Then we can talk about additions and upgrades.
My best
Mimmo

Inviato da iPad

**Comment by magomimmo** [comment]
Hi @suvash, today I got the time to take a look at it: very nice stuff. During the next xmas vacations I'll have the time to integrate it and the workaround about :none compilation option when using clojurescript.test in the mean time the official cljs.test will be ready to be used.

My best
mimmo

**Comment by magomimmo** [comment]
Hi @suvash, unfortunally it's a lot of time I did not make any other improvment on cljs-start. Currently we're working a lot on cljs/nodejs platform. But I'm obviously avaliable in receiving pull requests which add figwheel to the picture.

my best
mimmo
